version: "3"

networks:
  web:
    external: true

services:
  caddy:
    container_name: caddy
    extends:
      file: ../global/docker-compose.yml
      service: global
    image: foundationkitty/mediatower:caddy
    networks:
      - web
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /opt/caddy/data:/data
      - /opt/caddy/config:/config
      - /opt/caddy/Caddyfile:/etc/caddy/Caddyfile
